---
title: "Titanice"
author: "vijayant"
date: "12 June 2018"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2) # Visualization
library(ggthemes) # Visualization
library(scales) # Visualization
library(dplyr) # Data manipulation
library(mice) # Imputation
library(randomForest) # Classification Algorithm

```


```{r cars}
train <- read.csv("C://Users/Administrator/Downloads/titanic/train (1).csv")
test <- read.csv("C://Users/Administrator/Downloads/titanic/test (1).csv")
View(full$Name)
full <- bind_rows(train, test)

str(full)

# Feature Engineering Section

full$Title <- gsub('(.*, )|(\\..*)', '', full$Name)
View(full$Title)

# Show title counts by sex
table(full$Sex, full$Title)

# Titles with very low cell counts to be combined to "rare" level
rare_title <- c('Dona', 'Lady', 'the Countess', 'Capt', 'Col',
                'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer')

# Also reassign mlle, mme, ms accordingly
full$Title[full$Title == 'Mlle'] <- 'Miss'
full$Title[full$Title == 'Mme'] <- 'Mrs'
full$Title[full$Title == 'Ms'] <- 'Miss'
full$Title[full$Title %in% rare_title] <- 'Rare Title'

table(full$Sex, full$Title)



# Finally grab surname from passenger name
full$Surname <- sapply(full$Name,
                       function(x) strsplit(x, split = '[,.]')[[1]][1])
nlevels(factor(full$Surname))


# Create a family size variable including the passenger themselves

full$Fsize <- full$SibSp + full$Parch + 1
# Create a family variable
full$Family <- paste(full$Surname, full$Fsize, sep = '_')
View(full$Family)

# Use ggplot2 to visualize the relationship between family size and survival
ggplot(full[1:891, ], aes(x = Fsize, fill = factor(Survived))) +
  geom_bar(stat = 'count', position = 'dodge') +
  scale_x_continuous(breaks = c(1:11))


# Discretize family size
full$FsizeD[full$Fsize == 1] <- 'singleton'
full$FsizeD[full$Fsize > 1 & full$Fsize < 5] <- 'small'
full$FsizeD[full$Fsize > 4] <- 'large'


# Show family size by survival using mosaic plot
mosaicplot(table(full$FsizeD, full$Survived), 
           main = 'Family size by survival',
           shade = T,legend=T)

# We can see that there's a survival penalty to singletons and 
# those with family sizes above 4


full$Cabin[1:28]

# The first character is the deck name, For example
strsplit(full$Cabin[2], NULL)[[1]]

# Create a deck variable, get passenger deck A-F
full$Deck <- factor(sapply(full$Cabin, function(x) strsplit(x, NULL)[[1]][1]))
View(full$Deck)

# Missingness

full[c(62, 830), 'Embarked']

cat(paste('We will infer their values for **embarkment** 
          based on present data that we can imagine may be 
          relevant: **passenger class** and **fare**. 
          We see that they paid<b> $', full[c(62, 830), 'Fare'][[1]][1], 
          '</b>and<b> $', full[c(62, 830), 'Fare'][[1]][2], 
          '</b>respectively and their classes are<b>', 
          full[c(62, 830), 'Pclass'][[1]][1], '</b>and<b>', 
          full[c(62, 830), 'Pclass'][[1]][2], '</b>. So from where 
          did they embark?'))


embark_fare <- full %>%
  filter(PassengerId != 62 & PassengerId != 830)



ggplot(embark_fare, aes(x = Embarked, y = Fare, fill = factor(Pclass))) +
  geom_boxplot() +
  geom_hline(aes(yintercept = 80), colour = 'red',
             linetype = 'dashed', lwd = 2) +
  scale_y_continuous(labels = dollar_format()) +
  theme_few()

#The median fare for a first class passenger departing from 
# Charbourg ('C') coincides nicely with the $80 paid by our 
# embarkment-deficient passengers. I think we can safely replace 
# the NA values with 'C'.

# Since their fare was $80 for 1st class, they most likely embarked from 'C'
full$Embarked[c(62, 830)] <- 'C'

ggplot(full[full$Pclass == '3' & full$Embarked == 'S', ], aes(x = Fare)) +
  geom_density(fill = '#99d6ff', alpha = 0.4) +
  geom_vline(aes(xintercept = median(Fare, na.rm = T)),
             colour = 'red', linetype = 'dashed', lwd = 1) +
  scale_x_continuous(labels = dollar_format()) +
  theme_few()

# From this visualization, it seems reasonable to replace the 
# NA Fare value with median for their class and embarkment which is $8.05.

# Replace missing fair value with median fare class/embarkment
full$Fare[1044] <- median(full[full$Pclass == '3' &
                                 full$Embarked == 'S', ]$Fare, na.rm = T)

#age variable missing for mice imputation

sum(is.na(full$Age))

str(full)
# Make variables factors into factors
factor_vars <- c('PassengerId','Pclass','Sex','Embarked',
                 'Title','Surname','Family','FsizeD')

full[factor_vars] <- lapply(full[factor_vars], function(x) as.factor(x))

# Set a random seed
set.seed(129)

# Perform mice imputation, excluding certain less-than-useful variables
mice_mod <- mice(full[, !names(full) %in% c('PassengerId', 'Name', 
                                            'Ticket', 'Cabin',
                                            'Family', 'Surname',
                                            'Survived')], method = 'rf')

# Save the complete output
mice_output <- complete(mice_mod)


hist(full$Age, freq = F, main = 'Age: Original Data',
     col = 'darkgreen', ylim = c(0, 0.04))
hist(mice_output$Age, freq = F, main = 'Age: MICE output',
     col = 'lightgreen', ylim = c(0, 0.04))

# Replace age variable from the mice model.
full$Age <- mice_output$Age
sum(is.na(full$Age))

# First we'll look at the relationship between age and survival
ggplot(full[1:891, ], aes(Age, fill = factor(Survived))) +
  geom_histogram() +
  # I include Sex since we know (a priori) it's a significant predictor
  facet_grid(.~Sex)


full$Child[full$Age < 18] <- 'Child'
full$Child[full$Age >= 18] <- 'Adult'

table(full$Child, full$Survived)

# Adding mother variable
full$Mother <- 'Not Mother'
full$Mother[full$Sex == 'female' & 
              full$Parch > 0 &
              full$Age > 18 &
              full$Title != 'Miss'] <- 'Mother'

# Show counts
table(full$Mother, full$Survived)

# Finish by factorizing our two new factor variables
full$Child  <- factor(full$Child)
full$Mother <- factor(full$Mother)
md.pattern(full)
View(full)


# Split the data back into a train set and a test set
train <- full[1:891,]
test <- full[892:1309,]

# Building the model

# We then build our model using randomForest on the training set.

# Set a random seed
set.seed(754)

# Build the model (note: not all possible variables are used)
rf_model <- randomForest(factor(Survived) ~ Pclass +
                           Sex + Age + SibSp + Parch +
                           Fare + Embarked + Title +
                           FsizeD + Child + Mother,
                         data = train)

# Show model error
plot(rf_model, ylim = c(0, 0.36))

# Predict using the test set
prediction <- predict(rf_model, test)

# Save the solution to a dataframe with two columns: PassengerId and Survived (prediction)
solution <- data.frame(PassengerID = test$PassengerId, 
                       Survived = prediction)

# Write the solution to file
write.csv(solution, file = 'titanic_Solution.csv', row.names = F)

 ```



```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
